### ISSUE TITLE
(root) Additional property name is not allowed

### ISSUE THREAD

**Issue by ericvlog** [ben-2357/Torrentio-sh-Setup-Guide#2]
when i docker-compose up -d for install torrentio-sh it state (root) Additional property name is not allowed.

how do i get rid of it ? 

Thanks.

**Comment by ben-2357** [comment]
You need to run `docker compose up -d` to start the stack. I believe I have it this way in the guide. What you were trying to run, with the extra hyphen, was for an old version of Docker compose.
